### ISSUE TITLE
C4,C5,C6,C7 BOM differ from Design file

### ISSUE THREAD

**Issue by jcherrabi** [hallard/RAK3172-Breakout#3]
Hello @hallard 
your BOM shows and your readme writes that those are 100uF but your design show C4,C5,C6 are 10uF and only C7 100uF which is correct?

`PS : 100uF 0805 capacitors C4,C5,C6 and C7 are for use with coin cell battery, no need to put them if not powering from coin. Also take care of contact is using cell coin.`

![image](https://user-images.githubusercontent.com/5914393/152797402-69ebbdee-606e-4eeb-be44-9d328795ec20.png)

Jay

**Comment by hallard** [comment]
Thank for pointing that out, it's all 100uF fixed in V1.1
